'use strict'

/**
 * Events supported by CoLearnr
 */
const Events = {
  LEARNBIT_CREATED: 'LEARNBIT_CREATED',
  LEARNBIT_UPDATED: 'LEARNBIT_UPDATED',
  LEARNBIT_DELETED: 'LEARNBIT_DELETED',
  LEARNBIT_RESTORED: 'LEARNBIT_RESTORED',
  LEARNBIT_LINKED: 'LEARNBIT_LINKED',
  LEARNBIT_SHARED: 'LEARNBIT_SHARED',
  LEARNBIT_DISCUSSED: 'LEARNBIT_DISCUSSED',
  LEARNBIT_LIKED: 'LEARNBIT_LIKED',
  LEARNBIT_UNLIKED: 'LEARNBIT_UNLIKED',
  LEARNBIT_OPTIMISED: 'LEARNBIT_OPTIMISED',
  LEARNBIT_EXTRACTED: 'LEARNBIT_EXTRACTED',

  TOPIC_CREATED: 'TOPIC_CREATED',
  TOPIC_UPDATED: 'TOPIC_UPDATED',
  TOPIC_DELETED: 'TOPIC_DELETED',
  TOPIC_RESTORED: 'TOPIC_RESTORED',
  TOPIC_LINKED: 'TOPIC_LINKED',
  TOPIC_SHARED: 'TOPIC_SHARED',
  TOPIC_DISCUSSED: 'TOPIC_DISCUSSED',
  TOPIC_LIKED: 'TOPIC_LIKED',
  TOPIC_UNLIKED: 'TOPIC_UNLIKED',
  TOPIC_OPTIMISED: 'TOPIC_OPTIMISED',
  TOPIC_EXTRACTED: 'TOPIC_EXTRACTED',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_SHARED: 'USER_SHARED',
  USER_LIKED: 'USER_LIKED',
  USER_UNLIKED: 'USER_UNLIKED'
}

module.exports = Events
